name: docs-clean-action
description: Delete revision from storage

inputs:
  revision:
    required: true
  storage-bucket:
    required: true
  storage-endpoint:
    required: true
  storage-access-key-id:
    required: true
  storage-secret-access-key:
    required: true
  storage-region:
    required: true

runs:
  using: composite
  steps:
    - run: mkdir -p void # create placeholder dir
      shell: bash
    - name: Delete revision from storage
      uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
      with:
        args: --delete
      env:
        DEST_DIR: "rev/${{ inputs.revision }}"
        SOURCE_DIR: "void"
        AWS_S3_BUCKET: ${{ inputs.storage-bucket }}
        AWS_S3_ENDPOINT: ${{ inputs.storage-endpoint }}
        AWS_ACCESS_KEY_ID: ${{ inputs.storage-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.storage-secret-access-key }}
        AWS_REGION: ${{ inputs.storage-region }}
